import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "YN News",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="header">Header</header>
        <main className="main">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
